### ISSUE TITLE
Avoid Wildcard Imports for Better Code Maintainability

### ISSUE THREAD

**Issue by xWuWux** [Conso1eCowb0y/Deepminer#2]
The current implementation of Deepminer includes wildcard imports (`from modules.deephelpers import *` and `from modules.deepsqlite import *`). While wildcard imports may seem convenient, they introduce potential issues, including naming conflicts and decreased code maintainability.

Recommendation:

To improve the code quality and reduce the risk of naming conflicts, I suggest replacing wildcard imports with explicit imports of only the necessary functions or classes. This approach enhances code readability and makes it clear which components are being used from each module.

Example:

Replace:
`from modules.deephelpers import *
from modules.deepsqlite import *`

with explicit imports:

`from modules.deephelpers import function1, function2, ClassA
from modules.deepsqlite import connectDB, createTables, addDeepData`

Benefits:

Avoid Naming Conflicts: Explicit imports prevent naming conflicts by clearly specifying which components are used.
Improved Code Readability: Developers can easily understand which functions or classes are utilized in each part of the code.
Enhanced Maintainability: Explicit imports make it easier to track dependencies, aiding in future maintenance and updates.

Steps to Reproduce:

Identify all the functions and classes used from `deephelpers` and `deepsqlite` modules.
Replace wildcard imports with explicit imports based on the identified components.

Additional Notes:

Consider incorporating this change to align with best practices for Python coding standards and enhance the overall quality of the Deepminer codebase.

**Comment by rlfree** [comment]
This repo is now archived.
